import Foundation

extension Curriculum {

    static let kindergarten: [Skill] = [

        // ---------- Story Mode ----------
        Skill(id: "K-STORY1", grade: 0, subject: .reading,
              title: "Story: The Day the Sun Slept In",
              standard: "CA CCSS RL.K.1-10",
              activity: "Read a farm story, then play games about it. Stars Bodhi and Kona the dogs!",
              parentTip: "Read it together first. This one story covers all the Kindergarten reading skills.",
              lesson: .story(id: "sun-slept-in")),

        Skill(id: "K-MATH1", grade: 0, subject: .math,
              title: "Counting Critters",
              standard: "CA CCSS K.CC.1-7",
              activity: "Count, compare, and find out how many with the Counting Critters!",
              parentTip: "Covers all the Kindergarten counting and comparing skills.",
              lesson: .story(id: "counting-critters")),

        Skill(id: "K-MATH2", grade: 0, subject: .math,
              title: "Gabriel's Family of 10",
              standard: "CA CCSS K.OA.1-5",
              activity: "Add and take away with Gabriel's 7 cats, 2 dogs, and 1 Gabriel!",
              parentTip: "Addition and subtraction to 10, built on the family of 10.",
              lesson: .story(id: "family-add")),

        Skill(id: "K-MATH3", grade: 0, subject: .math,
              title: "Sort the Farm Animals",
              standard: "CA CCSS K.MD.3",
              activity: "Sort the chickens, sheep, cats, and dogs into their groups, then count how many are in each!",
              parentTip: "Sorting into categories and counting each group. Uses our real farm: lots of chickens, just a couple of dogs.",
              lesson: .story(id: "farm-sort")),

        Skill(id: "K-MATH4", grade: 0, subject: .math,
              title: "Shape Detective",
              standard: "CA CCSS K.G.2",
              activity: "Find the circle, square, triangle, rectangle, and hexagon by name or by how many sides!",
              parentTip: "Naming and describing flat shapes. He learns each shape's name and its number of sides.",
              lesson: .story(id: "shapes")),

        Skill(id: "K-MATH5", grade: 0, subject: .math,
              title: "Shape Spotter",
              standard: "CA CCSS K.G.2",
              activity: "Find every triangle, even the small or turned ones! Spot each shape no matter its size or which way it faces.",
              parentTip: "Naming shapes regardless of size or orientation. A triangle is still a triangle when it is tiny or rotated.",
              lesson: .story(id: "shape-spot")),

        Skill(id: "K-MATH10", grade: 0, subject: .math,
              title: "Build a Shape",
              standard: "CA CCSS K.G.6",
              activity: "Put shapes together to make a picture! A triangle and a square make a house. Tap the missing shape to finish each one.",
              parentTip: "Composing simple shapes into a bigger shape. At home, build pictures from blocks or cut-paper shapes together.",
              lesson: .story(id: "build-shape")),

        Skill(id: "K-MATH11", grade: 0, subject: .math,
              title: "Where Is It?",
              standard: "CA CCSS K.G.1",
              activity: "On top, under, or next to? Tap the picture that matches the words!",
              parentTip: "Position words. Narrate them at home: the cat is ON the chair, the ball is UNDER the table.",
              lesson: .story(id: "position-words")),

        Skill(id: "K-MATH12", grade: 0, subject: .math,
              title: "Count the Legs!",
              standard: "CA CCSS K.CC.4",
              activity: "Count the animal's legs, then drag it to that number!",
              parentTip: "Counting to tell how many. Count the legs on your real animals together.",
              lesson: .sort(prompt: "Count its legs, then put it in that pen.",
                            bins: [SortBin("two", "2 legs", "2"), SortBin("four", "4 legs", "4"),
                                   SortBin("six", "6 legs", "6"), SortBin("eight", "8 legs", "8")],
                            items: [
                              SortThing("🐔", "hen", "two"), SortThing("🦆", "duck", "two"),
                              SortThing("🦉", "owl", "two"), SortThing("🦜", "parrot", "two"),
                              SortThing("🐶", "dog", "four"), SortThing("🐮", "cow", "four"),
                              SortThing("🐴", "horse", "four"), SortThing("🐐", "goat", "four"),
                              SortThing("🐝", "bee", "six"), SortThing("🐞", "ladybug", "six"),
                              SortThing("🐜", "ant", "six"), SortThing("🦗", "cricket", "six"),
                              SortThing("🕷️", "spider", "eight"), SortThing("🦂", "scorpion", "eight"),
                              SortThing("🐙", "octopus", "eight")
                            ])),

        Skill(id: "K-MATH16", grade: 0, subject: .math,
              title: "Make 10",
              standard: "CA CCSS K.OA.4",
              activity: "Some animals are here. Tap how many MORE make 10!",
              parentTip: "Making ten with a missing part. Practice on fingers: 6 and 4 more make 10.",
              lesson: .story(id: "make-10")),

        Skill(id: "K-MATH17", grade: 0, subject: .math,
              title: "Take Away",
              standard: "CA CCSS K.OA.1",
              activity: "Some animals hop away. Count how many are LEFT!",
              parentTip: "Subtraction within 10 by taking away. Act it out with toys or snacks.",
              lesson: .story(id: "take-away")),

        Skill(id: "K-MATH18", grade: 0, subject: .math,
              title: "Doubles",
              standard: "CA CCSS 1.OA.6",
              activity: "Double it! 2 and 2 more makes 4. Tap the total!",
              parentTip: "Doubles facts — quick building blocks for adding. Say them like a chant.",
              lesson: .story(id: "doubles")),

        Skill(id: "K-MATH19", grade: 0, subject: .math,
              title: "First, Second, Third",
              standard: "CA CCSS K.CC.4",
              activity: "Who is first, second, third? Count from the front and tap it!",
              parentTip: "Ordinal numbers. Line up toys and name their places together.",
              lesson: .story(id: "ordinals")),

        Skill(id: "K-R11", grade: 0, subject: .reading,
              title: "Beginning Sounds",
              standard: "CA CCSS RF.K.3",
              activity: "Which sound does it start with? Carry each picture to its letter!",
              parentTip: "Letter-sound matching. Say the animal's name slowly: b-b-bear.",
              lesson: .sort(prompt: "Say the picture's name. Which sound does it start with?",
                            bins: [SortBin("m", "", "M"), SortBin("s", "", "S"),
                                   SortBin("t", "", "T"), SortBin("b", "", "B")],
                            items: [
                              SortThing("🐒", "monkey", "m"), SortThing("🌙", "moon", "m"),
                              SortThing("☀️", "sun", "s"), SortThing("🧦", "sock", "s"),
                              SortThing("🐯", "tiger", "t"), SortThing("🍅", "tomato", "t"),
                              SortThing("🐻", "bear", "b"), SortThing("🍌", "banana", "b")
                            ], perRound: 6)),

        Skill(id: "K-S14", grade: 0, subject: .science,
              title: "Growing Up",
              standard: "CA NGSS 1-LS1-1",
              activity: "Put the chicken's life in order, from egg to hen!",
              parentTip: "Life cycles. Talk about how your animals grow from babies.",
              lesson: .order(prompt: "How does a chick grow up? Put it in order.",
                             items: ["🥚 Egg", "🐣 Hatching", "🐥 Chick", "🐔 Hen"])),

        Skill(id: "K-MATH20", grade: 0, subject: .math,
              title: "Count by 10s",
              standard: "CA CCSS K.CC.1",
              activity: "Ten, twenty, thirty... tap what comes next when you count by tens!",
              parentTip: "Skip counting by tens. Count in groups of ten together.",
              lesson: .story(id: "count-tens")),

        Skill(id: "K-S15", grade: 0, subject: .science,
              title: "Fast or Slow",
              standard: "CA NGSS K-PS2-1",
              activity: "Fast or slow? Carry each animal to its pen!",
              parentTip: "Comparing how things move. Talk about fast and slow animals you know.",
              lesson: .sort(prompt: "Is it FAST or SLOW? Carry each animal to its pen.",
                            bins: [SortBin("fast", "Fast", "💨"), SortBin("slow", "Slow", "🐢")],
                            items: [
                              SortThing("🐆", "cheetah", "fast"), SortThing("🐇", "rabbit", "fast"),
                              SortThing("🐎", "horse", "fast"), SortThing("🦅", "eagle", "fast"),
                              SortThing("🐌", "snail", "slow"), SortThing("🦥", "sloth", "slow"),
                              SortThing("🐛", "caterpillar", "slow"), SortThing("🐨", "koala", "slow")
                            ], perRound: 6)),

        Skill(id: "K-S16", grade: 0, subject: .science,
              title: "Sink or Float",
              standard: "CA NGSS 2-PS1-1",
              activity: "Sink or float? Carry each thing to the water!",
              parentTip: "Predicting sink or float. Try it in the bath or a bowl of water together.",
              lesson: .sort(prompt: "Will it FLOAT on top or SINK to the bottom? Carry it over.",
                            bins: [SortBin("float", "Floats", "🛟"), SortBin("sink", "Sinks", "⚓️")],
                            items: [
                              SortThing("🦆", "rubber duck", "float"), SortThing("🍃", "leaf", "float"),
                              SortThing("⛵️", "boat", "float"), SortThing("🪵", "log", "float"),
                              SortThing("🪨", "rock", "sink"), SortThing("🔑", "key", "sink"),
                              SortThing("🥄", "spoon", "sink"), SortThing("🪙", "coin", "sink")
                            ], perRound: 6)),

        Skill(id: "K-R12", grade: 0, subject: .reading,
              title: "Big & Little Letters",
              standard: "CA CCSS RF.K.1d",
              activity: "Carry each little letter to its big letter!",
              parentTip: "Matching uppercase and lowercase. Point them out on signs and books.",
              lesson: .sort(prompt: "Carry each little letter to its big letter.",
                            bins: [SortBin("a", "", "A"), SortBin("b", "", "B"),
                                   SortBin("d", "", "D"), SortBin("e", "", "E")],
                            items: [
                              SortThing("a", "little a", "a"), SortThing("b", "little b", "b"),
                              SortThing("d", "little d", "d"), SortThing("e", "little e", "e")
                            ], perRound: 4)),

        Skill(id: "K-S17", grade: 0, subject: .science,
              title: "Five Senses",
              standard: "CA NGSS K-LS1",
              activity: "Which sense do you use? Carry each one to its sense!",
              parentTip: "The five senses. Name which sense you're using during the day.",
              lesson: .sort(prompt: "Which sense tells you about it? Carry it to that pen.",
                            bins: [SortBin("see", "See", "👀"), SortBin("hear", "Hear", "👂"),
                                   SortBin("smell", "Smell", "👃"), SortBin("taste", "Taste", "👅")],
                            items: [
                              SortThing("🌈", "a rainbow", "see"), SortThing("🎆", "fireworks", "see"),
                              SortThing("🔔", "a bell", "hear"), SortThing("🥁", "a drum", "hear"),
                              SortThing("🌸", "a flower", "smell"), SortThing("🦨", "a skunk", "smell"),
                              SortThing("🍋", "a lemon", "taste"), SortThing("🍦", "ice cream", "taste")
                            ], perRound: 6)),

        Skill(id: "K-R13", grade: 0, subject: .reading,
              title: "Opposites",
              standard: "CA CCSS L.K.5b",
              activity: "Drag in the opposite to finish each sentence!",
              parentTip: "Opposite words. Play an opposites game while you walk or cook.",
              lesson: .buildSentence(prompt: "Drag in the OPPOSITE to finish the sentence.", lines: [
                SentenceLine("🐘", "An elephant is big. A mouse is", "", answer: "little", distractors: ["big", "hot"]),
                SentenceLine("🔥", "Fire is hot. Snow is", "", answer: "cold", distractors: ["hot", "up"]),
                SentenceLine("☀️", "The sun is out in the day. The moon is out at", "", answer: "night", distractors: ["day", "fast"]),
                SentenceLine("🐆", "A cheetah is fast. A snail is", "", answer: "slow", distractors: ["fast", "sad"]),
                SentenceLine("🎈", "The balloon goes up. The rain comes", "", answer: "down", distractors: ["up", "big"]),
                SentenceLine("😀", "I was sad. Now I am", "", answer: "happy", distractors: ["cold", "down"])
              ])),

        Skill(id: "K-S6", grade: 0, subject: .science,
              title: "Animal Homes",
              standard: "CA NGSS K-ESS3-1",
              activity: "Where does each animal live? Drag it home to the farm, the ocean, the snow or the jungle!",
              parentTip: "Animals and where they live. Talk about where your farm animals live vs. ocean or jungle animals.",
              lesson: .sort(prompt: "Take each animal home. Farm, ocean, snow or jungle?",
                            bins: [SortBin("farm", "Farm", "🚜"), SortBin("ocean", "Ocean", "🌊"),
                                   SortBin("snow", "Snow", "❄️"), SortBin("jungle", "Jungle", "🌴")],
                            items: [
                              SortThing("🐮", "cow", "farm"), SortThing("🐔", "hen", "farm"),
                              SortThing("🐷", "pig", "farm"), SortThing("🐑", "sheep", "farm"),
                              SortThing("🐠", "fish", "ocean"), SortThing("🐙", "octopus", "ocean"),
                              SortThing("🦀", "crab", "ocean"), SortThing("🐬", "dolphin", "ocean"),
                              SortThing("🐧", "penguin", "snow"), SortThing("🐻‍❄️", "polar bear", "snow"),
                              SortThing("🦭", "seal", "snow"), SortThing("🦌", "reindeer", "snow"),
                              SortThing("🐒", "monkey", "jungle"), SortThing("🦜", "parrot", "jungle"),
                              SortThing("🐆", "leopard", "jungle"), SortThing("🐍", "snake", "jungle")
                            ])),

        Skill(id: "K-S7", grade: 0, subject: .science,
              title: "Fur, Feathers, Scales",
              standard: "CA NGSS 1-LS1-1",
              activity: "Is it covered in fur, feathers, or scales? Drag each animal to its coat!",
              parentTip: "Animal body coverings. Feel your animals' fur and feathers together.",
              lesson: .sort(prompt: "What is it covered in? Fur, feathers or scales?",
                            bins: [SortBin("fur", "Fur", "🧸"), SortBin("feathers", "Feathers", "🪶"),
                                   SortBin("scales", "Scales", "🐟")],
                            items: [
                              SortThing("🐶", "dog", "fur"), SortThing("🐱", "cat", "fur"),
                              SortThing("🐻", "bear", "fur"), SortThing("🐑", "sheep", "fur"),
                              SortThing("🐰", "rabbit", "fur"), SortThing("🦊", "fox", "fur"),
                              SortThing("🐔", "hen", "feathers"), SortThing("🦆", "duck", "feathers"),
                              SortThing("🦉", "owl", "feathers"), SortThing("🦢", "swan", "feathers"),
                              SortThing("🦅", "eagle", "feathers"), SortThing("🦜", "parrot", "feathers"),
                              SortThing("🐟", "fish", "scales"), SortThing("🐍", "snake", "scales"),
                              SortThing("🐊", "crocodile", "scales"), SortThing("🦎", "lizard", "scales")
                            ], perRound: 9)),

        Skill(id: "K-S8", grade: 0, subject: .science,
              title: "What Do Animals Eat?",
              standard: "CA NGSS K-LS1",
              activity: "Every animal eats! Drag the food to the animal that wants it.",
              parentTip: "What animals need to live. Talk about what you feed your animals each day.",
              lesson: .sort(prompt: "Feeding time on the farm. Who gets which food?",
                            bins: [SortBin("hen", "Hen", "🐔"), SortBin("goat", "Goat", "🐐"),
                                   SortBin("cat", "Cat", "🐱"), SortBin("horse", "Horse", "🐴")],
                            items: [
                              SortThing("🌽", "corn", "hen"), SortThing("🌾", "grain", "hen"),
                              SortThing("🥬", "greens", "goat"), SortThing("🌿", "weeds", "goat"),
                              SortThing("🐟", "fish", "cat"), SortThing("🥛", "milk", "cat"),
                              SortThing("🥕", "carrot", "horse"), SortThing("🍎", "apple", "horse")
                            ])),

        Skill(id: "K-R16", grade: 0, subject: .reading,
              title: "Letter Sounds",
              standard: "CA CCSS RF.K.3a",
              activity: "Say the picture. Carry it to the letter it starts with!",
              parentTip: "Sound first, letter second. Say the sound with him: /g/, /g/, goat.",
              lesson: .sort(prompt: "Leo says each picture. Carry it to the letter it starts with.",
                            bins: [SortBin("g", "", "G"), SortBin("h", "", "H"),
                                   SortBin("j", "", "J"), SortBin("l", "", "L")],
                            items: [
                              SortThing("🐐", "goat", "g"), SortThing("🎁", "gift", "g"),
                              SortThing("🐴", "horse", "h"), SortThing("🎩", "hat", "h"),
                              SortThing("🧃", "juice", "j"), SortThing("🪁", "jump rope", "j"),
                              SortThing("🦁", "lion", "l"), SortThing("🍋", "lemon", "l")
                            ], perRound: 6)),

        Skill(id: "K-R14", grade: 0, subject: .reading,
              title: "Syllable Safari",
              standard: "CA CCSS RF.K.2",
              activity: "Tap each beat of the animal's name and clap it. Then count the claps!",
              parentTip: "Breaking words into syllables. Clap names together — RAB-BIT, EL-E-PHANT.",
              lesson: .story(id: "syllables")),

        Skill(id: "K-S18", grade: 0, subject: .science,
              title: "Animal Groups",
              standard: "CA NGSS K-LS1",
              activity: "Mammal, bird, fish or bug? Carry each animal to its group!",
              parentTip: "Sorting animals into groups by their traits (fur, feathers, scales, fins, six legs).",
              lesson: .sort(prompt: "Fur, feathers, fins or six legs? Carry each animal to its group.",
                            bins: [SortBin("mammal", "Mammals (fur)", "🐻"), SortBin("bird", "Birds (feathers)", "🪶"),
                                   SortBin("fish", "Fish (fins)", "🐠"), SortBin("bug", "Bugs (6 legs)", "🐞")],
                            items: [
                              SortThing("🐮", "cow", "mammal"), SortThing("🐶", "dog", "mammal"), SortThing("🐴", "horse", "mammal"),
                              SortThing("🐔", "hen", "bird"), SortThing("🦉", "owl", "bird"), SortThing("🦆", "duck", "bird"),
                              SortThing("🐟", "trout", "fish"), SortThing("🐡", "pufferfish", "fish"), SortThing("🦈", "shark", "fish"),
                              SortThing("🐝", "bee", "bug"), SortThing("🐜", "ant", "bug"), SortThing("🦋", "butterfly", "bug")
                            ], perRound: 6)),

        Skill(id: "K-S19", grade: 0, subject: .science,
              title: "Animal Sounds",
              standard: "CA NGSS K-LS1",
              activity: "Who says it? Carry each animal to its sound!",
              parentTip: "Animal sounds. Make the sounds together and guess the animal.",
              lesson: .sort(prompt: "Listen to each animal. Carry it to the sound it makes.",
                            bins: [SortBin("moo", "Moo", "🔊"), SortBin("oink", "Oink", "🔊"),
                                   SortBin("baa", "Baa", "🔊"), SortBin("cluck", "Cluck", "🔊")],
                            items: [
                              SortThing("🐄", "cow", "moo"), SortThing("🐮", "calf", "moo"),
                              SortThing("🐖", "pig", "oink"), SortThing("🐷", "piglet", "oink"),
                              SortThing("🐑", "sheep", "baa"), SortThing("🐏", "ram", "baa"),
                              SortThing("🐔", "hen", "cluck"), SortThing("🐓", "rooster", "cluck")
                            ], perRound: 6)),

        Skill(id: "K-S20", grade: 0, subject: .science,
              title: "Four Seasons",
              standard: "CA NGSS K-ESS2-1",
              activity: "Winter, spring, summer or fall? Carry each thing to its season!",
              parentTip: "The four seasons and their weather. Talk about what changes each season.",
              lesson: .sort(prompt: "When do you see it? Carry each one to its season.",
                            bins: [SortBin("winter", "Winter", "❄️"), SortBin("spring", "Spring", "🌷"),
                                   SortBin("summer", "Summer", "☀️"), SortBin("fall", "Fall", "🍂")],
                            items: [
                              SortThing("⛄️", "snowman", "winter"), SortThing("🧤", "mittens", "winter"),
                              SortThing("🐣", "baby chicks", "spring"), SortThing("🌸", "blossoms", "spring"),
                              SortThing("🏖️", "the beach", "summer"), SortThing("🍉", "watermelon", "summer"),
                              SortThing("🎃", "pumpkins", "fall"), SortThing("🍁", "falling leaves", "fall")
                            ], perRound: 6)),

        Skill(id: "K-S21", grade: 0, subject: .science,
              title: "Swim, Fly, or Walk?",
              standard: "CA NGSS K-LS1",
              activity: "Does the animal swim, fly, or walk? Drag each one to how it moves!",
              parentTip: "How animals move. Point out swimmers, fliers, and walkers when you're outside.",
              lesson: .sort(prompt: "How does it get around? Swim, fly or walk?",
                            bins: [SortBin("swim", "Swims", "🌊"), SortBin("fly", "Flies", "🕊️"),
                                   SortBin("walk", "Walks", "🐾")],
                            items: [
                              SortThing("🐟", "fish", "swim"), SortThing("🐬", "dolphin", "swim"),
                              SortThing("🦈", "shark", "swim"), SortThing("🐙", "octopus", "swim"),
                              SortThing("🦅", "eagle", "fly"), SortThing("🦋", "butterfly", "fly"),
                              SortThing("🐝", "bee", "fly"), SortThing("🦇", "bat", "fly"),
                              SortThing("🐶", "dog", "walk"), SortThing("🐘", "elephant", "walk"),
                              SortThing("🐴", "horse", "walk"), SortThing("🐈", "cat", "walk")
                            ], perRound: 9)),

        Skill(id: "K-MATH21", grade: 0, subject: .math,
              title: "Count by 5s",
              standard: "CA CCSS K.CC.1",
              activity: "Count by fives! 5, 10, 15... Tap the number that comes next.",
              parentTip: "Skip counting by 5s. Count hands and fingers together — 5, 10, 15.",
              lesson: .story(id: "count-5s")),

        Skill(id: "K-MATH22", grade: 0, subject: .math,
              title: "Count by 2s",
              standard: "CA CCSS K.CC.1",
              activity: "Count by twos! 2, 4, 6... Tap the number that comes next.",
              parentTip: "Skip counting by 2s. Count pairs — eyes, ears, socks — 2, 4, 6.",
              lesson: .story(id: "count-2s")),

        Skill(id: "K-R15", grade: 0, subject: .reading,
              title: "Baby Animal Names",
              standard: "CA CCSS L.K.5",
              activity: "Baby animals have special names. Carry each grown-up to its baby!",
              parentTip: "Animal vocabulary. Quiz each other on baby animal names.",
              lesson: .sort(prompt: "Carry each grown-up to its baby. Leo will say the baby's name.",
                            bins: [SortBin("lamb", "Lamb", "🐑"), SortBin("foal", "Foal", "🐴"),
                                   SortBin("piglet", "Piglet", "🐷"), SortBin("duckling", "Duckling", "🐥")],
                            items: [
                              SortThing("🐏", "sheep", "lamb"), SortThing("🐎", "horse", "foal"),
                              SortThing("🐖", "pig", "piglet"), SortThing("🦆", "duck", "duckling")
                            ], perRound: 4)),

        Skill(id: "K-S22", grade: 0, subject: .science,
              title: "Parts of a Plant",
              standard: "CA NGSS K-LS1",
              activity: "Root, leaf, flower or fruit? Carry each plant part to its pen!",
              parentTip: "Parts of a plant and their jobs. Look at a real plant together.",
              lesson: .sort(prompt: "Which part of the plant do we see? Carry it to its pen.",
                            bins: [SortBin("root", "Roots", "🟫"), SortBin("leaf", "Leaves", "🍃"),
                                   SortBin("flower", "Flowers", "🌼"), SortBin("fruit", "Fruit", "🍎")],
                            items: [
                              SortThing("🥕", "carrot", "root"), SortThing("🫚", "ginger", "root"),
                              SortThing("🥬", "lettuce", "leaf"), SortThing("🌿", "herbs", "leaf"),
                              SortThing("🌷", "tulip", "flower"), SortThing("🌻", "sunflower", "flower"),
                              SortThing("🍓", "strawberry", "fruit"), SortThing("🍅", "tomato", "fruit")
                            ], perRound: 6)),

        Skill(id: "K-S23", grade: 0, subject: .science,
              title: "Hot or Cold?",
              standard: "CA NGSS K-PS3",
              activity: "Hot or cold? Carry each one to its pen!",
              parentTip: "Temperature — hot vs cold. Point out hot and cold things at home.",
              lesson: .sort(prompt: "Is it HOT or COLD? Carry it to its pen.",
                            bins: [SortBin("hot", "Hot", "🔥"), SortBin("cold", "Cold", "🧊")],
                            items: [
                              SortThing("☀️", "the sun", "hot"), SortThing("☕️", "hot cocoa", "hot"),
                              SortThing("🌋", "a volcano", "hot"), SortThing("🍲", "soup", "hot"),
                              SortThing("⛄️", "a snowman", "cold"), SortThing("🍦", "ice cream", "cold"),
                              SortThing("🐧", "a penguin's home", "cold"), SortThing("❄️", "snow", "cold")
                            ], perRound: 6)),

        Skill(id: "K-MATH13", grade: 0, subject: .math,
              title: "Teen Numbers",
              standard: "CA CCSS K.NBT.1",
              activity: "A teen number is ten and some more! Count the ten plus the extras and tap the number.",
              parentTip: "Teen numbers as ten and ones. Build 10 with objects, then add a few more.",
              lesson: .story(id: "teen-numbers")),

        Skill(id: "K-S9", grade: 0, subject: .science,
              title: "Baby Animals",
              standard: "CA NGSS 1-LS3-1",
              activity: "Carry each baby to its grown-up!",
              parentTip: "Young animals resemble their parents. Look at baby and grown animals together.",
              lesson: .sort(prompt: "Carry each baby to its grown-up.",
                            bins: [SortBin("hen", "Hen", "🐔"), SortBin("pig", "Pig", "🐖"),
                                   SortBin("horse", "Horse", "🐎"), SortBin("rabbit", "Rabbit", "🐇")],
                            items: [
                              SortThing("🐣", "chick", "hen"), SortThing("🐷", "piglet", "pig"),
                              SortThing("🐴", "foal", "horse"), SortThing("🐰", "bunny", "rabbit")
                            ], perRound: 4)),

        Skill(id: "K-S10", grade: 0, subject: .science,
              title: "Alive or Not? On the Farm",
              standard: "CA NGSS K-LS1",
              activity: "Living things grow, eat, and move! Drag each one into the right pen.",
              parentTip: "Characteristics of living things. Point out what's alive vs. an object on a walk.",
              lesson: .sort(prompt: "Does it grow and eat? Then it is alive. Drag each one where it goes.",
                            bins: [SortBin("alive", "Alive", "🌱"), SortBin("not", "Not alive", "🧱")],
                            items: [
                              SortThing("🐔", "hen", "alive"), SortThing("🐐", "goat", "alive"),
                              SortThing("🌻", "sunflower", "alive"), SortThing("🐝", "bee", "alive"),
                              SortThing("🦋", "butterfly", "alive"), SortThing("🌵", "cactus", "alive"),
                              SortThing("🐑", "sheep", "alive"), SortThing("🍄", "mushroom", "alive"),
                              SortThing("🚜", "tractor", "not"), SortThing("🪣", "bucket", "not"),
                              SortThing("🧱", "brick", "not"), SortThing("🔔", "bell", "not"),
                              SortThing("🥾", "boot", "not"), SortThing("🪑", "stool", "not"),
                              SortThing("🔑", "key", "not"), SortThing("🧤", "glove", "not")
                            ])),

        Skill(id: "K-S11", grade: 0, subject: .science,
              title: "Day or Night?",
              standard: "CA NGSS K-ESS1",
              activity: "Owls and bats wake at night, bees buzz in the day. Drag each animal to when it wakes!",
              parentTip: "Day and night patterns in animal behavior. Talk about which animals you see when.",
              lesson: .sort(prompt: "When is it awake? Put each animal under the sun or the moon.",
                            bins: [SortBin("day", "Awake in the day", "☀️"), SortBin("night", "Awake at night", "🌙")],
                            items: [
                              SortThing("🐝", "bee", "day"), SortThing("🦋", "butterfly", "day"),
                              SortThing("🐔", "hen", "day"), SortThing("🐿️", "squirrel", "day"),
                              SortThing("🐶", "dog", "day"), SortThing("🐴", "horse", "day"),
                              SortThing("🦉", "owl", "night"), SortThing("🦇", "bat", "night"),
                              SortThing("🦝", "raccoon", "night"), SortThing("🦔", "hedgehog", "night"),
                              SortThing("🦊", "fox", "night"), SortThing("🐸", "frog", "night")
                            ])),

        Skill(id: "K-MATH14", grade: 0, subject: .math,
              title: "Make 5",
              standard: "CA CCSS K.OA.4",
              activity: "Some animals are here! Tap how many more make 5.",
              parentTip: "Making 5 from two parts. Use fingers or beans to show 3 and 2 make 5.",
              lesson: .story(id: "make-5")),

        Skill(id: "K-MATH15", grade: 0, subject: .math,
              title: "Which Has More?",
              standard: "CA CCSS K.CC.6",
              activity: "Two groups of animals! Tap the group with more, or with fewer.",
              parentTip: "Comparing groups. Line up two sets of objects and compare which has more.",
              lesson: .story(id: "which-more")),

        Skill(id: "K-S12", grade: 0, subject: .science,
              title: "Egg or Not?",
              standard: "CA NGSS K-LS1",
              activity: "Which animals hatch from eggs? Drag each one to how it was born.",
              parentTip: "How animals have young. Hens lay eggs; puppies are born live.",
              lesson: .sort(prompt: "Did it hatch from an egg, or was it born? Drag each animal over.",
                            bins: [SortBin("egg", "Hatched from an egg", "🥚"),
                                   SortBin("born", "Born like a puppy", "🐶")],
                            items: [
                              SortThing("🐔", "hen", "egg"), SortThing("🦆", "duck", "egg"),
                              SortThing("🐢", "turtle", "egg"), SortThing("🐍", "snake", "egg"),
                              SortThing("🐸", "frog", "egg"), SortThing("🐟", "fish", "egg"),
                              SortThing("🦅", "eagle", "egg"), SortThing("🐊", "crocodile", "egg"),
                              SortThing("🐶", "puppy", "born"), SortThing("🐱", "kitten", "born"),
                              SortThing("🐮", "calf", "born"), SortThing("🐴", "foal", "born"),
                              SortThing("🐑", "lamb", "born"), SortThing("🐷", "piglet", "born"),
                              SortThing("🐰", "rabbit", "born"), SortThing("🐐", "kid goat", "born")
                            ])),

        Skill(id: "K-S13", grade: 0, subject: .science,
              title: "Wild or Pet?",
              standard: "CA NGSS K-LS1",
              activity: "Pets live with us, wild animals live on their own. Drag each one home!",
              parentTip: "Classifying animals. Talk about your pets vs. animals at the zoo.",
              lesson: .sort(prompt: "Does it live with people, or out on its own? Take it home.",
                            bins: [SortBin("pet", "Lives with us", "🏠"), SortBin("wild", "Lives in the wild", "🌲")],
                            items: [
                              SortThing("🐶", "dog", "pet"), SortThing("🐱", "cat", "pet"),
                              SortThing("🐹", "hamster", "pet"), SortThing("🐴", "horse", "pet"),
                              SortThing("🐮", "cow", "pet"), SortThing("🐔", "hen", "pet"),
                              SortThing("🐠", "goldfish", "pet"), SortThing("🐰", "rabbit", "pet"),
                              SortThing("🦁", "lion", "wild"), SortThing("🐻", "bear", "wild"),
                              SortThing("🦊", "fox", "wild"), SortThing("🐘", "elephant", "wild"),
                              SortThing("🦒", "giraffe", "wild"), SortThing("🐺", "wolf", "wild"),
                              SortThing("🦌", "deer", "wild"), SortThing("🦉", "owl", "wild")
                            ])),

        Skill(id: "K-MATH9", grade: 0, subject: .math,
              title: "Bigger or Smaller?",
              standard: "CA CCSS K.MD.2",
              activity: "Compare two things! Which is bigger, taller, or heavier? Which is smaller, shorter, or lighter?",
              parentTip: "Comparing size, height, and weight. Compare real objects around the house together.",
              lesson: .story(id: "bigger-smaller")),

        Skill(id: "K-MATH7", grade: 0, subject: .math,
              title: "What Comes Next?",
              standard: "CA CCSS K (Patterns)",
              activity: "Look at the color pattern and tap what comes next! Red, blue, red, blue...",
              parentTip: "Recognizing and extending patterns. Try clap-stomp body patterns together too.",
              lesson: .story(id: "patterns")),

        Skill(id: "K-MATH8", grade: 0, subject: .math,
              title: "Flat or Solid?",
              standard: "CA CCSS K.G.3",
              activity: "Some shapes are flat like a circle, some are solid like a ball. Tell which is which!",
              parentTip: "Flat (2D) vs solid (3D) shapes. Hold a ball, a box, and a can while you play.",
              lesson: .story(id: "flat-or-solid")),

        Skill(id: "K-S5", grade: 0, subject: .science,
              title: "Plant or Animal?",
              standard: "CA NGSS K-LS1",
              activity: "Sort living things! Which is a plant, which is an animal, which can fly, which lives in water?",
              parentTip: "Sorting plants and animals by observable characteristics. Spot living things together on a walk.",
              lesson: .story(id: "plant-or-animal")),

        Skill(id: "K-R10", grade: 0, subject: .reading,
              title: "Rhyme Time",
              standard: "CA CCSS RF.K.2a",
              activity: "Carry each picture to the words it rhymes with!",
              parentTip: "Rhyming is a key reading sound skill. Say the words aloud together to hear the rhyme.",
              lesson: .sort(prompt: "Say it out loud. Which family does it rhyme with?",
                            bins: [SortBin("ee", "bee, tree", "🐝"), SortBin("ar", "star, car", "⭐️"),
                                   SortBin("ox", "fox, box", "🦊"), SortBin("oon", "moon, spoon", "🌙")],
                            items: [
                              SortThing("🔑", "key", "ee"), SortThing("🍵", "tea", "ee"),
                              SortThing("🫙", "jar", "ar"), SortThing("🎸", "guitar", "ar"),
                              SortThing("🧦", "socks", "ox"), SortThing("📦", "box", "ox"),
                              SortThing("🎈", "balloon", "oon"), SortThing("🥄", "spoon", "oon")
                            ], perRound: 6)),

        Skill(id: "K-MATH6", grade: 0, subject: .math,
              title: "Number Detective",
              standard: "CA CCSS K.CC.4",
              activity: "Count the dots and find the number, or read the number and find the group that shows it!",
              parentTip: "Connecting numbers to how many. He counts a group and matches it to the numeral, both directions.",
              lesson: .story(id: "number-detective")),

        // ---------- Reading ----------
        Skill(id: "K-R1", grade: 0, subject: .reading,
              title: "Capital Letter Detective",
              standard: "CA CCSS RF.K.1d",
              activity: "Big letter or little letter? Carry each one to its pen!",
              parentTip: "Big letters start sentences and names. Let him say each one aloud.",
              lesson: .sort(prompt: "Is it a BIG (capital) letter or a little letter?",
                            bins: [SortBin("big", "Big letters", "A"), SortBin("little", "Little letters", "a")],
                            items: [
                              SortThing("B", "big B", "big"), SortThing("G", "big G", "big"),
                              SortThing("R", "big R", "big"), SortThing("M", "big M", "big"),
                              SortThing("b", "little b", "little"), SortThing("g", "little g", "little"),
                              SortThing("r", "little r", "little"), SortThing("m", "little m", "little")
                            ], perRound: 6)),

        Skill(id: "K-R2", grade: 0, subject: .reading,
              title: "Match the Letter Buddies",
              standard: "CA CCSS RF.K.1d",
              activity: "Every big letter has a little buddy. Tap a letter, then tap its partner!",
              parentTip: "Matching big to small builds letter recognition both ways.",
              lesson: .match(prompt: "Match the big letter to its little buddy.",
                             pairs: [.init("A", "a"), .init("B", "b"),
                                     .init("C", "c"), .init("D", "d")])),

        Skill(id: "K-R3", grade: 0, subject: .reading,
              title: "Letter Sounds Safari",
              standard: "CA CCSS RF.K.3a",
              activity: "Letters make sounds. Drag every animal to the sound it starts with!",
              parentTip: "Say the sound, not the letter name: /k/, not 'see'.",
              lesson: .sort(prompt: "Listen to the first sound. Which pen does it belong in?",
                            bins: [SortBin("k", "/k/  like cat", "🐱"),
                                   SortBin("s", "/s/  like sun", "☀️"),
                                   SortBin("h", "/h/  like hen", "🐔")],
                            items: [
                              SortThing("🐮", "cow", "k"), SortThing("🚗", "car", "k"),
                              SortThing("🥤", "cup", "k"), SortThing("👑", "crown", "k"),
                              SortThing("🧦", "sock", "s"), SortThing("🐍", "snake", "s"),
                              SortThing("🌱", "seed", "s"), SortThing("🥄", "spoon", "s"),
                              SortThing("🎩", "hat", "h"), SortThing("🐴", "horse", "h"),
                              SortThing("🏠", "house", "h"), SortThing("🍯", "honey", "h")
                            ], perRound: 9)),

        Skill(id: "K-R4", grade: 0, subject: .reading,
              title: "Barnyard Rhyme Time",
              standard: "CA CCSS RF.K.2a",
              activity: "Rhyming words sound alike at the end. Send each word to the animal it rhymes with!",
              parentTip: "Say the words out loud together so he hears the rhyme.",
              lesson: .sort(prompt: "Which farm animal does it rhyme with? Drag it over.",
                            bins: [SortBin("hen", "hen", "🐔"), SortBin("cat", "cat", "🐱"),
                                   SortBin("pig", "pig", "🐷")],
                            items: [
                              SortThing("🖊️", "pen", "hen"), SortThing("🔟", "ten", "hen"),
                              SortThing("👨", "men", "hen"), SortThing("🇩🇰", "den", "hen"),
                              SortThing("🎩", "hat", "cat"), SortThing("🦇", "bat", "cat"),
                              SortThing("🐀", "rat", "cat"), SortThing("🧉", "mat", "cat"),
                              SortThing("💇", "wig", "pig"), SortThing("⛏️", "dig", "pig"),
                              SortThing("🫒", "fig", "pig"), SortThing("🌿", "twig", "pig")
                            ], perRound: 9)),

        Skill(id: "K-R5", grade: 0, subject: .reading,
              title: "Sound It Out",
              standard: "CA CCSS RF.K.2c",
              activity: "Stretch the sounds, snap them together, then carry them to the picture!",
              parentTip: "Robot-talk the sounds slowly, then blend fast.",
              lesson: .sort(prompt: "Stretch the sounds, snap them together, and carry them to the picture.",
                            bins: [SortBin("hen", "", "🐔"), SortBin("bug", "", "🐛"),
                                   SortBin("fox", "", "🦊"), SortBin("bat", "", "🦇")],
                            items: [
                              SortThing("h e n", "h, e, n", "hen"), SortThing("b u g", "b, u, g", "bug"),
                              SortThing("f o x", "f, o, x", "fox"), SortThing("b a t", "b, a, t", "bat"),
                            ], perRound: 4)),

        Skill(id: "K-R6", grade: 0, subject: .reading,
              title: "Star Words",
              standard: "CA CCSS RF.K.3c",
              activity: "Read the little sentence and drag in the star word that fits!",
              parentTip: "Star words (see, go, is, like, and…) show up in every sentence. He reads the whole sentence and picks the word that makes sense — reading, not just matching. Read it aloud together with each choice if he's stuck.",
              // Reading-in-context, NOT shape-matching. The star word is the gap,
              // so he has to read the sentence to know which word fits, then
              // drag it in. A picture anchors the meaning.
              lesson: .buildSentence(prompt: "Read the sentence. Drag in the star word that fits.", lines: [
                SentenceLine("🐶", "I", "the dog.", answer: "see", distractors: ["go", "is"]),
                SentenceLine("🚜", "We", "to the tractor.", answer: "go", distractors: ["is", "see"]),
                SentenceLine("🐔", "The hen", "here.", answer: "is", distractors: ["and", "go"]),
                SentenceLine("🐰", "I", "my bunny.", answer: "like", distractors: ["to", "is"]),
                SentenceLine("🐷", "The pig", "the cow play.", answer: "and", distractors: ["is", "go"]),
                SentenceLine("🍎", "This snack is", "me.", answer: "for", distractors: ["up", "see"])
              ])),

        Skill(id: "K-R7", grade: 0, subject: .reading,
              title: "What Happens First?",
              standard: "CA CCSS RL.K.2",
              activity: "Stories happen in order. Put the day in the right order!",
              parentTip: "Sequencing a familiar routine builds story retelling.",
              lesson: .order(prompt: "Put the day in order, first to last.",
                             items: ["Wake up", "Eat breakfast", "Play outside", "Go to bed"])),

        Skill(id: "K-R8", grade: 0, subject: .reading,
              title: "How Books Work",
              standard: "CA CCSS RF.K.1a",
              activity: "Books have a secret map. Put the words in reading order, left to right!",
              parentTip: "These print rules make reading click.",
              lesson: .order(prompt: "We read left to right. Put the words in reading order.",
                             items: ["The", "hen", "sat", "on", "her", "eggs."])),

        Skill(id: "K-R9", grade: 0, subject: .reading,
              title: "Letter Detective",
              standard: "CA CCSS RF.K.1d / RF.K.3a",
              activity: "Find the letters! Carry each one to its matching pen!",
              parentTip: "Letter recognition and letter sounds. Say the sound, not the name: /b/, not 'bee'.",
              lesson: .sort(prompt: "Carry each letter, big or little, to its pen.",
                            bins: [SortBin("g", "", "G"), SortBin("h", "", "H"),
                                   SortBin("j", "", "J"), SortBin("k", "", "K")],
                            items: [
                              SortThing("g", "little g", "g"), SortThing("G", "big G", "g"),
                              SortThing("h", "little h", "h"), SortThing("H", "big H", "h"),
                              SortThing("j", "little j", "j"), SortThing("J", "big J", "j"),
                              SortThing("k", "little k", "k"), SortThing("K", "big K", "k")
                            ], perRound: 6)),

        // ---------- Writing (hands-on) ----------
        Skill(id: "K-W1", grade: 0, subject: .writing,
              title: "Write Your Name",
              standard: "CA CCSS L.K.1a",
              activity: "Trace each letter of your name with your finger!",
              parentTip: "Tracing the letters of his name with a finger is real early handwriting.",
              lesson: .trace(prompt: "Trace your name!",
                             items: ["G", "A", "B", "R", "I", "E", "L"])),

        Skill(id: "K-W2", grade: 0, subject: .writing,
              title: "Trace Capital Letters",
              standard: "CA CCSS L.K.1a",
              activity: "Trace each big capital letter with your finger!",
              parentTip: "Forming capital letters by tracing builds handwriting control.",
              lesson: .trace(prompt: "Trace the letters!",
                             items: ["A", "B", "C", "D", "E", "F"])),

        Skill(id: "K-W3", grade: 0, subject: .writing,
              title: "Label the Animal",
              standard: "CA CCSS W.K.2",
              activity: "Labeling is writing the first letter. Trace the starting letter of each animal!",
              parentTip: "Hearing the first sound and writing its letter is early labeling/writing.",
              lesson: .trace(prompt: "Trace the first letter!",
                             items: ["C", "P", "H", "D", "S"])),

        // ----- More writing practice (Gabriel is choosing to write on screen
        // and succeeding — writing is one of his harder skills, so lean in with
        // numbers, the rest of the alphabet, and his family's names). -----
        Skill(id: "K-W4", grade: 0, subject: .writing,
              title: "Write 1 to 5!",
              standard: "CA CCSS K.CC.3",
              activity: "Write the numbers! Trace each one with your finger.",
              parentTip: "He's great with numbers — now he writes them. Say the number as he traces it.",
              lesson: .trace(prompt: "Trace the number!",
                             items: ["1", "2", "3", "4", "5"])),

        Skill(id: "K-W5", grade: 0, subject: .writing,
              title: "Write 6 to 10!",
              standard: "CA CCSS K.CC.3",
              activity: "Write the bigger numbers! Trace each one with your finger.",
              parentTip: "Writing numbers cements what he already counts. Zero is a nice round loop.",
              lesson: .trace(prompt: "Trace the number!",
                             items: ["6", "7", "8", "9", "0"])),

        Skill(id: "K-W6", grade: 0, subject: .writing,
              title: "Letters G to L",
              standard: "CA CCSS L.K.1a",
              activity: "More capital letters! Trace each one with your finger.",
              parentTip: "A few letters at a time. Trace slowly; neatness comes with practice.",
              lesson: .trace(prompt: "Trace the letter!",
                             items: ["G", "H", "I", "J", "K", "L"])),

        Skill(id: "K-W7", grade: 0, subject: .writing,
              title: "Letters M to R",
              standard: "CA CCSS L.K.1a",
              activity: "Keep going through the alphabet! Trace each letter.",
              parentTip: "He's building the whole alphabet now. Cheer each finished letter.",
              lesson: .trace(prompt: "Trace the letter!",
                             items: ["M", "N", "O", "P", "Q", "R"])),

        Skill(id: "K-W8", grade: 0, subject: .writing,
              title: "Letters S to Z",
              standard: "CA CCSS L.K.1a",
              activity: "The last letters of the alphabet! Trace each one.",
              parentTip: "Finishing the alphabet is a big deal — make it a celebration.",
              lesson: .trace(prompt: "Trace the letter!",
                             items: ["S", "T", "U", "V", "W", "X", "Y", "Z"])),

        Skill(id: "K-W9", grade: 0, subject: .writing,
              title: "Write Mama's Name",
              standard: "CA CCSS L.K.1a",
              activity: "Write a name you love! Trace each letter of PAIGE.",
              parentTip: "Writing a family name is meaningful practice. Say each letter with him: P-A-I-G-E.",
              lesson: .trace(prompt: "Trace the letter!",
                             items: ["P", "A", "I", "G", "E"])),

        // ---------- Math ----------
        // Concrete "count what you see" number games — built in Gabriel's
        // winning style to attack the number gaps his miss data revealed.
        Skill(id: "K-NUM1", grade: 0, subject: .math,
              title: "Count the Critters",
              standard: "CA CCSS K.CC.4",
              activity: "Count the animals, then type how many!",
              parentTip: "He has to actually count and type the number — no guessing from choices.",
              lesson: .numberGen(.count, rounds: 5)),

        Skill(id: "K-NUM2", grade: 0, subject: .math,
              title: "How Many in All?",
              standard: "CA CCSS K.OA.1",
              activity: "Put both groups together, count them ALL, and type it!",
              parentTip: "Adding as 'put together and count all,' then producing the number.",
              lesson: .numberGen(.add, rounds: 4)),

        Skill(id: "K-NUM3", grade: 0, subject: .math,
              title: "Count by 2s",
              standard: "CA CCSS K.CC.1",
              activity: "Count the pairs 2 at a time, then type how many!",
              parentTip: "Real pairs make the 'skip' visible; typing the total can't be guessed.",
              lesson: .numberGen(.skipTwos, rounds: 4)),

        Skill(id: "K-NUM4", grade: 0, subject: .math,
              title: "Count by 5s",
              standard: "CA CCSS K.CC.1",
              activity: "Each hand is 5 fingers. Count by 5s and type it!",
              parentTip: "Hands give him a built-in group of 5; he skip-counts and types the total.",
              lesson: .numberGen(.skipFives, rounds: 4)),

        Skill(id: "K-M1", grade: 0, subject: .math,
              title: "Count to 20",
              standard: "CA CCSS K.CC.1",
              activity: "Tap each animal and count out loud all the way to 20!",
              parentTip: "Counting things he can see keeps it concrete.",
              lesson: .count(target: 20, symbol: "pawprint.fill",
                             prompt: "Tap each paw and count to 20!")),

        Skill(id: "K-M2", grade: 0, subject: .math,
              title: "Count by Tens",
              standard: "CA CCSS K.CC.1",
              activity: "Big numbers zoom by tens. Put them in order!",
              parentTip: "Clap on each ten to add rhythm.",
              lesson: .order(prompt: "Tap the tens in order.",
                             items: ["10", "20", "30", "40", "50", "60", "70", "80", "90", "100"])),

        Skill(id: "K-M3", grade: 0, subject: .math,
              title: "Count the Eggs",
              standard: "CA CCSS K.CC.4",
              activity: "Touch one egg for each number. Count carefully to 10!",
              parentTip: "One tap per number builds one-to-one counting.",
              lesson: .count(target: 10, symbol: "circle.fill",
                             prompt: "Tap each egg as you count to 10!")),

        Skill(id: "K-M4", grade: 0, subject: .math,
              title: "Number Order 0-10",
              standard: "CA CCSS K.CC.3",
              activity: "Numbers have an order too. Line them up from 0 to 10!",
              parentTip: "Recognizing order supports writing the numbers.",
              lesson: .order(prompt: "Tap the numbers in order.",
                             items: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"])),

        Skill(id: "K-M5", grade: 0, subject: .math,
              title: "Who Has More?",
              standard: "CA CCSS K.CC.4-6",
              activity: "Count each group, then carry it to MORE than 5 or FEWER than 5!",
              parentTip: "Connect to snacks: 'who has more?' and count up together.",
              lesson: .sort(prompt: "Count each group. MORE than 5, or FEWER than 5?",
                            bins: [SortBin("more", "More than 5", "🖐️➕"), SortBin("fewer", "Fewer than 5", "🖐️➖")],
                            items: [
                              SortThing("🍎🍎🍎🍎🍎🍎🍎", "apples", "more"), SortThing("🐥🐥🐥🐥🐥🐥", "chicks", "more"),
                              SortThing("🥚🥚🥚🥚🥚🥚🥚🥚", "eggs", "more"), SortThing("🐟🐟🐟🐟🐟🐟🐟🐟🐟", "fish", "more"),
                              SortThing("🍓🍓", "berries", "fewer"), SortThing("🐸🐸🐸", "frogs", "fewer"),
                              SortThing("🐝", "bee", "fewer"), SortThing("🥕🥕🥕🥕", "carrots", "fewer")
                            ], perRound: 6)),

        Skill(id: "K-M6", grade: 0, subject: .math,
              title: "Adding On",
              standard: "CA CCSS K.OA.1",
              activity: "Put groups together to make more. Solve each one!",
              parentTip: "Let him use fingers or beans to check.",
              lesson: .numberPad([
                NumberProblem("3 eggs + 2 eggs = ?", 5),
                NumberProblem("4 + 1 = ?", 5),
                NumberProblem("2 + 2 = ?", 4)
              ])),

        Skill(id: "K-M7", grade: 0, subject: .math,
              title: "Taking Away",
              standard: "CA CCSS K.OA.1",
              activity: "Some go away, and you find what's left. Solve each one!",
              parentTip: "Act it out with carrots and a hungry bunny.",
              lesson: .numberPad([
                NumberProblem("5 carrots - 2 = ?", 3),
                NumberProblem("4 - 1 = ?", 3),
                NumberProblem("5 - 5 = ?", 0)
              ])),

        Skill(id: "K-M8", grade: 0, subject: .math,
              title: "2D Shape Hunt",
              standard: "CA CCSS K.G.2",
              activity: "Carry each thing to the shape it looks like!",
              parentTip: "Spot these shapes together on a walk.",
              lesson: .sort(prompt: "Circle, square or triangle? Carry each one to its shape.",
                            bins: [SortBin("circle", "Circle", "⚪️"), SortBin("square", "Square", "🟥"), SortBin("triangle", "Triangle", "🔺")],
                            items: [
                              SortThing("🍪", "cookie", "circle"), SortThing("🕛", "clock", "circle"),
                              SortThing("🎁", "present", "square"), SortThing("🧇", "waffle", "square"),
                              SortThing("🍕", "pizza slice", "triangle"), SortThing("⛺️", "tent", "triangle")
                            ], perRound: 6)),

        Skill(id: "K-M9", grade: 0, subject: .math,
              title: "Solid Shapes",
              standard: "CA CCSS K.G.2",
              activity: "Ball, box or can? Carry each thing to its solid shape!",
              parentTip: "Hold a ball, a box, and a can while you play.",
              lesson: .sort(prompt: "Sphere, cube or cylinder? Carry each one to its shape.",
                            bins: [SortBin("sphere", "Sphere", "⚽️"), SortBin("cube", "Cube", "🧊"), SortBin("cylinder", "Cylinder", "🥫")],
                            items: [
                              SortThing("🏀", "basketball", "sphere"), SortThing("🌍", "globe", "sphere"),
                              SortThing("🎲", "dice", "cube"), SortThing("📦", "box", "cube"),
                              SortThing("🥤", "cup", "cylinder"), SortThing("🕯️", "candle", "cylinder")
                            ], perRound: 6)),

        Skill(id: "K-M10", grade: 0, subject: .math,
              title: "Which One Is Different?",
              standard: "CA CCSS K.MD.3",
              activity: "Animal, color or shape? Carry each one to its group!",
              parentTip: "Ask him to explain why it doesn't belong.",
              lesson: .sort(prompt: "Is it an animal, a food or a shape? Carry it to its group.",
                            bins: [SortBin("animal", "Animals", "🐮"), SortBin("food", "Food", "🍎"), SortBin("shape", "Shapes", "🔷")],
                            items: [
                              SortThing("🐔", "hen", "animal"), SortThing("🐴", "horse", "animal"),
                              SortThing("🍌", "banana", "food"), SortThing("🥕", "carrot", "food"),
                              SortThing("⭐️", "star", "shape"), SortThing("🔺", "triangle", "shape")
                            ], perRound: 6)),

        Skill(id: "K-M11", grade: 0, subject: .math,
              title: "What Comes Next?",
              standard: "CA CCSS K (Patterns)",
              activity: "Finish the pattern by putting the pieces in order!",
              parentTip: "Try clap-stomp body patterns too.",
              lesson: .order(prompt: "Make the pattern: sun, moon, sun, moon. Tap them in order.",
                             items: ["☀️", "🌙", "☀️", "🌙", "☀️", "🌙"])),

        // ---------- Science ----------
        Skill(id: "K-S1", grade: 0, subject: .science,
              title: "Weather Watcher",
              standard: "CA NGSS K-ESS2-1",
              activity: "Rainy, sunny or snowy? Carry each thing to the weather it's for!",
              parentTip: "Look out the window together first.",
              lesson: .sort(prompt: "Would you need it on a RAINY day, a SUNNY day or a SNOWY day?",
                            bins: [SortBin("rain", "Rainy", "🌧️"), SortBin("sun", "Sunny", "☀️"), SortBin("snow", "Snowy", "❄️")],
                            items: [
                              SortThing("🧥", "raincoat", "rain"), SortThing("☂️", "umbrella", "rain"),
                              SortThing("👒", "sun hat", "sun"), SortThing("🕶️", "sunglasses", "sun"),
                              SortThing("🧤", "mittens", "snow"), SortThing("🧣", "scarf", "snow")
                            ], perRound: 6)),

        Skill(id: "K-S2", grade: 0, subject: .science,
              title: "What They Need",
              standard: "CA NGSS K-LS1-1",
              activity: "What does a living thing need? Carry each one to its pen!",
              parentTip: "Walk to your plants and animals and talk about what they need.",
              lesson: .sort(prompt: "Do living things NEED it to live? Carry each one over.",
                            bins: [SortBin("need", "Living things need it", "🌱"), SortBin("toy", "Nice, but not needed", "🎈")],
                            items: [
                              SortThing("💧", "water", "need"), SortThing("☀️", "sunlight", "need"),
                              SortThing("🍎", "food", "need"), SortThing("🌬️", "air", "need"),
                              SortThing("📺", "a TV", "toy"), SortThing("🎮", "a game", "toy"),
                              SortThing("🧸", "a teddy bear", "toy"), SortThing("🎁", "a present", "toy")
                            ], perRound: 6)),

        Skill(id: "K-S3", grade: 0, subject: .science,
              title: "Push or Pull?",
              standard: "CA NGSS K-PS2-1",
              activity: "Push or pull? Carry each one to its pen!",
              parentTip: "Try it together with a cart, a door, and a wagon afterward.",
              lesson: .sort(prompt: "Do you PUSH it away or PULL it close? Carry it over.",
                            bins: [SortBin("push", "Push", "🫸"), SortBin("pull", "Pull", "🫷")],
                            items: [
                              SortThing("🛒", "shopping cart", "push"), SortThing("🧹", "broom", "push"),
                              SortThing("🛴", "scooter", "push"), SortThing("⚽️", "kick a ball", "push"),
                              SortThing("🛷", "sled up the hill", "pull"), SortThing("🪢", "tug-of-war rope", "pull"),
                              SortThing("🪁", "kite string", "pull"), SortThing("🎣", "fishing line", "pull")
                            ], perRound: 6)),

        Skill(id: "K-S4", grade: 0, subject: .science,
              title: "Weather Watch",
              standard: "CA NGSS K-ESS2-1",
              activity: "What would you need? Carry each thing to its weather!",
              parentTip: "Observing and describing weather. Look out the window together and name today's weather.",
              lesson: .sort(prompt: "What would you need? Carry each thing to its weather.",
                            bins: [SortBin("sunny", "Sunny", "☀️"), SortBin("rainy", "Rainy", "🌧️"),
                                   SortBin("snowy", "Snowy", "❄️"), SortBin("windy", "Windy", "💨")],
                            items: [
                              SortThing("🕶️", "sunglasses", "sunny"), SortThing("👒", "sun hat", "sunny"),
                              SortThing("☂️", "umbrella", "rainy"), SortThing("🥾", "rain boots", "rainy"),
                              SortThing("🧤", "mittens", "snowy"), SortThing("🛷", "sled", "snowy"),
                              SortThing("🪁", "kite", "windy"), SortThing("🍃", "blowing leaves", "windy")
                            ], perRound: 6)),

        // ---------- Social Studies ----------
        Skill(id: "K-SS1", grade: 0, subject: .life,
              title: "American Symbols",
              standard: "CA HSS K.2",
              activity: "Is it an American symbol? Carry each one to its pen!",
              parentTip: "Identifying national symbols. Point them out on money, at school, and around town.",
              lesson: .sort(prompt: "Is it an American symbol? Carry each one to its pen.",
                            bins: [SortBin("symbol", "American symbols", "🇺🇸"), SortBin("not", "Not a symbol", "🙅")],
                            items: [
                              SortThing("🗽", "Statue of Liberty", "symbol"), SortThing("🦅", "bald eagle", "symbol"),
                              SortThing("🔔", "Liberty Bell", "symbol"), SortThing("🏛️", "White House", "symbol"),
                              SortThing("🍕", "pizza", "not"), SortThing("🚲", "bike", "not"),
                              SortThing("🧸", "teddy bear", "not"), SortThing("🐸", "frog", "not")
                            ], perRound: 6)),

        Skill(id: "K-SS2", grade: 0, subject: .life,
              title: "Community Helpers",
              standard: "CA HSS K.3",
              activity: "Whose tool is it? Carry each tool to its helper!",
              parentTip: "Identifying helpers in school and the community. Talk about helpers you meet in daily life.",
              lesson: .sort(prompt: "Whose tool is it? Carry each one to the helper who uses it.",
                            bins: [SortBin("fire", "Firefighter", "🚒"), SortBin("doctor", "Doctor", "🩺"),
                                   SortBin("farmer", "Farmer", "🚜"), SortBin("chef", "Chef", "🍳")],
                            items: [
                              SortThing("🧯", "fire extinguisher", "fire"), SortThing("🪜", "tall ladder", "fire"),
                              SortThing("🌡️", "thermometer", "doctor"), SortThing("🩹", "bandage", "doctor"),
                              SortThing("🌽", "corn to plant", "farmer"), SortThing("🐄", "cow to milk", "farmer"),
                              SortThing("🥣", "mixing bowl", "chef"), SortThing("🍲", "soup pot", "chef")
                            ], perRound: 6)),

        Skill(id: "K-SS3", grade: 0, subject: .life,
              title: "Party on the Farm!",
              standard: "CA HSS K.1",
              activity: "Which party is it for? Carry each thing to its holiday!",
              parentTip: "Knowing what major holidays celebrate. Connect each to your own family traditions.",
              lesson: .sort(prompt: "Which holiday is it for? Carry each one to its party.",
                            bins: [SortBin("halloween", "Halloween", "🎃"), SortBin("thanks", "Thanksgiving", "🦃"),
                                   SortBin("july4", "Fourth of July", "🎆"), SortBin("valentine", "Valentine's Day", "💝")],
                            items: [
                              SortThing("👻", "ghost costume", "halloween"), SortThing("🍬", "candy", "halloween"),
                              SortThing("🥧", "pumpkin pie", "thanks"), SortThing("🌽", "corn", "thanks"),
                              SortThing("🇺🇸", "flag", "july4"), SortThing("🎇", "sparkler", "july4"),
                              SortThing("💌", "love card", "valentine"), SortThing("🌹", "rose", "valentine")
                            ], perRound: 6)),

        Skill(id: "K-SS4", grade: 0, subject: .life,
              title: "My Family",
              standard: "CA HSS K.3",
              activity: "Meet your family and what everyone does at home! Two moms, Mommy and Maddy, plus all the cats and dogs.",
              parentTip: "Naming family members and their roles. Families come in all kinds; this one celebrates yours.",
              lesson: .story(id: "my-family")),

        // ---------- Life Skills ----------
        Skill(id: "K-L1", grade: 0, subject: .life,
              title: "Name Your Feelings",
              standard: "CA SEL",
              activity: "Drag each face to the feeling it shows. A new mix of feelings every time!",
              parentTip: "No pressure to feel any of these, just to name them. Talk about times he's felt each one.",
              lesson: .faceMatch(exprs: FaceExpr.allCases, perRound: 3)),

        Skill(id: "K-L2", grade: 0, subject: .life,
              title: "Days of the Week",
              standard: "CA SEL / Calendar",
              activity: "The week repeats in order. Put the days in order!",
              parentTip: "A days-of-the-week song helps the order stick.",
              lesson: .order(prompt: "Tap the days in order.",
                             items: ["Sunday", "Monday", "Tuesday", "Wednesday",
                                     "Thursday", "Friday", "Saturday"])),

        Skill(id: "K-L3", grade: 0, subject: .life,
              title: "Farm Helpers",
              standard: "CA SEL / Self-help",
              activity: "Good helpers make the farm run. Tap the helpful choice!",
              parentTip: "Talk about real jobs he could pick afterward, his choice.",
              lesson: .quiz([
                // The wrong answers here are jokes, and he taps them on purpose
                // ("Blame the dog" every time). `jokes:` gets a laugh line and
                // is never counted as a miss, so this game stops reading as a
                // struggle in the dashboard.
                Question("A good helper job is...", correct: "Feeding the animals", wrong: [], jokes: ["Breaking toys", "Hiding shoes"]),
                Question("If you spill something, you...", correct: "Help clean it up", wrong: [], jokes: ["Run away", "Blame the dog"]),
                Question("A kind helper word is...", correct: "Please", wrong: [], jokes: ["No way", "Mine"])
              ]))
    ]
}
